### ISSUE TITLE
No result for feedback widget

### ISSUE THREAD

**Issue by mars3142** [Countly/countly-sdk-flutter-bridge#129]
The result of ```Countly.presentFeedbackWidget()``` is a future, but I never know, if the feedback was successful or canceled from user side. 

My tests shows, that the result is "appeared", which is shown immediately. How can I do to see, if the survey was canceled or fulfilled?

**Comment by turtledreams** [comment]
Hi! The `presentFeedbackWidget` function features two callbacks: “widget appeared” and “widget closed.” It’s important to note that these feedback widgets are not native views or UI elements; rather, they are WebView launched via a URL. All feedback-related interactions and handling are carried out within the WebView, and our native SDK does not provide access to these actions due to current limitations. As of now, we can only provide callbacks for when the widget is displayed and when it is closed.

However, we do offer a manual feedback reporting function. With this function, you can manually report feedback by creating a custom user interface for the widget. This custom UI will grant you full control over the actions performed within the widget.
For more details on how to implement manual feedback reporting, please refer to the following link: [Manual Reporting Feedback Widget](https://support.count.ly/hc/en-us/articles/360037944212-Flutter#h_01H930GAQ7HMVWZBVTXTCDTF50).

**Comment by mars3142** [comment]
```presentFeedbackWidget``` is a Future. How can it report 2 different results? It would be better to return after closing the webview a result and not at startup. So we can "await" a result und this is "canceled" or "fullfilled" or "what ever".

**Comment by ijunaid** [comment]
Hello @mars3142,
The `presentFeedbackWidget` function is future and accommodates two optional callback parameters: `widgetShown` and `widgetClosed`.
`widgetShown`: This callback triggers when the feedback page is loaded in the WebView.
`widgetClosed`: We’ve introduced a native close button within the WebView’s feedback UI. This callback is activated when the user taps on this close button.
It’s important to note that all feedback-related interactions and handling take place exclusively within the WebView. Unfortunately, due to current limitations, our native SDK does not provide access to these actions.

**Comment by turtledreams** [comment]
Also here is an example implementation for you to visualize @mars3142 :
```
// fetch available widgets from the server
FeedbackWidgetsResponse feedbackWidgetsResponse = await Countly.getAvailableFeedbackWidgets();

// present the first one from that list
await Countly.presentFeedbackWidget(feedbackWidgetsResponse.presentableFeedback.first, 'Close', widgetShown: () {
    print('Widget Appeared');
  }, widgetClosed: () {
    print('Widget Dismissed');
  });
});
```
