### ISSUE TITLE
local_auth >=1.1.0 is incompatible with countly_flutter 20.11.1

### ISSUE THREAD

**Issue by halkportal970** [Countly/countly-sdk-flutter-bridge#33]
When i used local_auth and countly package together. i got this error.

Because local_auth >=1.1.0 depends on flutter_plugin_android_lifecycle ^2.0.0 and countly_flutter 20.11.1 depends on flutter_plugin_android_lifecycle ^1.0.8, local_auth >=1.1.0 is incompatible with countly_flutter 20.11.1.

And because no versions of countly_flutter match >20.11.1 <21.0.0, local_auth >=1.1.0 is incompatible with countly_flutter ^20.11.1.

So, because beraber depends on both countly_flutter ^20.11.1 and local_auth ^1.1.0, version solving failed.
pub get failed (1; So, because beraber depends on both countly_flutter ^20.11.1 and local_auth ^1.1.0, version solving failed.)
exit code 1

**Comment by ijunaid** [comment]
Hi @halkportal970

This error occurs because both "countly_flutter" and "local_auth" are using the same "flutter_plugin_android_lifecycle" package with different versions.
You could try to override the version of "flutter_plugin_android_lifecycle" in your pubspec.yaml,  try to use the latest version of [flutter_plugin_android_lifecycle](https://pub.dev/packages/flutter_plugin_android_lifecycle)

```
dependency_overrides:
flutter_plugin_android_lifecycle: ^2.0.0
```

Let us know if this override helped your problem. We will be releasing a new SDK version with the updated plugin version in the coming weeks

**Comment by halkportal970** [comment]
thanks it solves our problem
